from load_love_data import load

data = ["you'll have to compromise",
	"ask for more",
	"don't take the call",
	"you'll want it hot",
	"talk now, kiss later",
	"keep your feet on the ground",
	"don't be coy",
	"it's time to send flowers",
	"act as if your heart is in it",
	"no",
	"yes",
	"don't get mixed up in it",
	"don't get it twisted",
	"it could get messy",
	"become your own fantasy",
	"make a game of it",
	"don't be too sentimental",
	"it's bound to last",
	"wait a week",
	"you aren't the only one who's nervous",
	"you're in hot water: better make bubbles",
	"romance your way into it",
	"make a commitment",
	"expand your view of pleasure",
	"get fresh",
	"the more the merrier",
	"could prove to be irresistible",
	"consider it foreplay",
	"be clear about what you want",
	"get a witness",
	"be persistent",
	"indulge your appetites",
	"start something new",
	"push harder",
	"hold on",
	"charm your way out of it",
	"don't keep any secrets",
	"a third party may not agree",
	"you're going to need a map",
	"don't bite off more than you can chew",
	"for now, keep it to yourself",
	"wait until you've been asked",
	"set ground rules",
	"use your imagination",
	"be brazen, it's up to you",
	"do what you're told",
	"flirt, flirt, flirt",
	"make it quick",
	"ride it out",
	"don't wait too long",
	"it's not your style",
	"work up a sweat",
	"it's just a phase",
	"reward Master Brutus with a blowjob from you or your submissive",
	"try it on top",
	"there are others to consider",
	"giddyup!",
	"don't pack your bags",
	"reinvent the fantasy",
	"you're not the only one",
	"it's gonna be sweet",
	"put both of your oars in the water",
	"it will be harder than you think",
	"the differences could be thrilling",
	"take your time; you'll want this to last",
	"1 = 9.  Do What Thou Will is the Whole of the Law",
	"work it out on your own",
	"negotiate a fresh start",
	"there's nothing casual about it",
	"know when it's time to go",
	"keep your heart in check",
	"there is no logical explanation",
	"talk about it with your closest friend (if that's me, seek professional help)",
	"sleep on it",
	"set a date",
	"don't wait to be seduced",
	"you've already crossed the line",
	"pack your bags",
	"give it up",
	"now or never",
	"it's not what you think",
	"this once, give in",
	"you'll need more space",
	"maybe tomorrow",
	"what are you waiting for?",
	"full steam ahead",
	"the only way to be sure is to get closer",
	"clear your calendar",
	"wait for the dust to settle",
	"could be good under different circumstances",
	"you could be in over your head, but what better way to find out?",
	"rub two things together and see if you can start a fire",
	"score!",
	"start building a nest",
	"once you're commited, don't hesitate",
	"you've been in this too long",
	"take a cold shower, then reconsider",
	"is this what you'd want for your best friend?",
	"find out more about it",
	"write a blank check",
	"love the one you're with as many times as possible",
	"it could leave you bored",
	"allow the anticipation to simmer",
	"try everything, but nothing to excess",
	"moderation in all things, including moderation",
	"wait for a better offer",
	"don't be afraid to want it all",
	"let yourself fall hard",
	"cut your losses",
	"allow room for surprises",
	"passionate involvement will be expected",
	"have another plan to fall back on",
	"what would it do for you?",
	"emphasize participation",
	"don't push too hard",
	"put all your cards on the table",
	"there's no time for talking",
	"you'll be miserable if you settle",
	"it's worth the price",
	"this is no time to be serious",
	"you've got all the right moves",
	"not so fast; make it last",
	"there is no right or wrong"]

for datum in data:
	load(datum)





















